package org.microworld.mangopay.entities;

public enum RefundReasonType {
  BANKACCOUNT_HAS_BEEN_CLOSED,
  BANKACCOUNT_INCORRECT,
  INITIALIZED_BY_CLIENT,
  OTHER,
  OWNER_DOT_NOT_MATCH_BANKACCOUNT,
  WITHDRAWAL_IMPOSSIBLE_ON_SAVINGS_ACCOUNTS;
}
